### PR TITLE
Helping

### PR DESCRIPTION
**Pull request by basarat**

### CODE REVIEW

**Comment by mikecann** [comment]
Hahaha I noticed that too ;)

**Comment by basarat** [comment]
@danielearwicker Just trying to help here. Can clean up PR / drop ideas based on review :rose:

**Comment by basarat** [comment]
> Hahaha I noticed that too ;)

Actually those imports prevent this tsc error : https://travis-ci.org/danielearwicker/immuto/jobs/160050143#L195 I honestly haven't seen it before. Just looking away 👀  for now :rose:

**Comment by basarat** [comment]
Put in an explicit tsc version because : https://travis-ci.org/danielearwicker/immuto/jobs/160053794#L191. Its just for our dev. Doesn't impact the version people use :rose:

**Review by basarat — COMMENTED** [review]
⚠️  Breaking Change. Feel free to batch it up with the next one.

**Comment by danielearwicker** [comment]
Thanks! 👍 

Re: the error about types that cannot be named, I had a report from someone about that error in another library, same problem, but they only got it in WebStorm. But with 2.0 rc I see it in command-line `tsc` builds. It feels like a TS bug to me.

**Comment by danielearwicker** [comment]
@basarat re: error about `has or is using name...`, [looks like](https://github.com/Microsoft/TypeScript/issues/5711) this is caused by `--declaration`. For apps that don't need to generate `.d.ts` it wouldn't be an issue.

**Pull request merged**
